// List of nations with their corresponding URLs
const nations = [
    { name: 'auburn', url: 'https://auburn.craigslist.org' },
    { name: 'birmingham', url: 'https://bham.craigslist.org' },
    { name: 'dothan', url: 'https://dothan.craigslist.org' },
    { name: 'florence / muscle shoals', url: 'https://shoals.craigslist.org' },
    { name: 'gadsden-anniston', url: 'https://gadsden.craigslist.org' },
    { name: 'huntsville / decatur', url: 'https://huntsville.craigslist.org' },
    { name: 'mobile', url: 'https://mobile.craigslist.org' },
    { name: 'montgomery', url: 'https://montgomery.craigslist.org' },
    { name: 'tuscaloosa', url: 'https://tuscaloosa.craigslist.org' },
    { name: 'anchorage / mat-su', url: 'https://anchorage.craigslist.org' },
    { name: 'fairbanks', url:'https://fairbanks.craigslist.org'},
    { name: 'kenai peninsula', url:'https://kenai.craigslist.org'},
    { name: 'southeast alaska', url:'https://juneau.craigslist.org'},
    { name: 'flagstaff / sedona', url:'https://flagstaff.craigslist.org'},
    { name: 'mohave county', url:'https://mohave.craigslist.org'},
    { name: 'phoenix', url:'https://phoenix.craigslist.org'},
    { name: 'prescott', url:'https://prescott.craigslist.org'},
    { name: 'show low', url:'https://showlow.craigslist.org'},
    { name: 'sierra vista', url:'https://sierravista.craigslist.org'},
    { name: 'tucson', url:'https://tucson.craigslist.org'},
    { name: 'yuma', url:'https://yuma.craigslist.org'},
    { name: 'fayetteville', url:'https://fayar.craigslist.org'},
    { name: 'fort smith', url:'https://fortsmith.craigslist.org'},
    { name: 'jonesboro', url:'https://jonesboro.craigslist.org'},
    { name: 'little rock', url:'https://littlerock.craigslist.org'},
    { name: 'texarkana', url:'https://texarkana.craigslist.org'},
    { name: 'bakersfield', url:'https://bakersfield.craigslist.org'},
    { name: 'chico', url:'https://chico.craigslist.org'},
    { name: 'fresno / madera', url:'https://fresno.craigslist.org'},
    { name: 'gold country', url:'https://goldcountry.craigslist.org'},
    { name: 'hanford-corcoran', url:'https://hanford.craigslist.org'},
    { name: 'humboldt county', url:'https://humboldt.craigslist.org'},
    { name: 'imperial county', url:'https://imperial.craigslist.org'},
    { name: 'inland empire', url:'https://inlandempire.craigslist.org'},
    { name: 'los angeles', url:'https://losangeles.craigslist.org'},
    { name: 'mendocino county', url:'https://mendocino.craigslist.org'},
    { name: 'merced', url:'https://merced.craigslist.org'},
    { name: 'modesto', url:'https://modesto.craigslist.org'},
    { name: 'monterey bay', url:'https://monterey.craigslist.org'},
    { name: 'orange county', url:'https://orangecounty.craigslist.org'},
    { name: 'palm springs', url:'https://palmsprings.craigslist.org'},
    { name: 'redding', url:'https://redding.craigslist.org'},
    { name: 'sacramento', url:'https://sacramento.craigslist.org'},
    { name: 'san diego', url:'https://sandiego.craigslist.org'},
    { name: 'san francisco bay area', url:'https://sfbay.craigslist.org'},
    { name: 'san luis obispo', url:'https://slo.craigslist.org'},
    { name: 'santa barbara', url:'https://santabarbara.craigslist.org'},
    { name: 'santa maria', url:'https://santamaria.craigslist.org'},
    { name: 'siskiyou county', url:'https://siskiyou.craigslist.org'},
    { name: 'stockton', url:'https://stockton.craigslist.org'},
    { name: 'susanville', url:'https://susanville.craigslist.org'},
    { name: 'ventura county', url:'https://ventura.craigslist.org'},
    { name: 'visalia-tulare', url:'https://visalia.craigslist.org'},
    { name: 'yuba-sutter', url:'https://yubasutter.craigslist.org'},
    { name: 'boulder', url:'https://boulder.craigslist.org'},
    { name: 'colorado springs', url:'https://cosprings.craigslist.org'},
    { name: 'denver', url:'https://denver.craigslist.org'},
    { name: 'eastern CO', url:'https://eastco.craigslist.org'},
    { name: 'fort collins / north CO', url:'https://fortcollins.craigslist.org'},
    { name: 'high rockies', url:'https://rockies.craigslist.org'},
    { name: 'pueblo', url:'https://pueblo.craigslist.org'},
    { name: 'western slope', url:'https://westslope.craigslist.org'},
    { name: 'eastern CT', url:'https://newlondon.craigslist.org'},
    { name: 'hartford', url:'https://hartford.craigslist.org'},
    { name: 'new haven', url:'https://newhaven.craigslist.org'},
    { name: 'northwest CT', url:'https://nwct.craigslist.org'},
    { name: 'delaware', url:'https://delaware.craigslist.org'},
    { name: 'washington', url:'https://washingtondc.craigslist.org'},
    { name: 'broward county', url:'https://miami.craigslist.org'},
    { name: 'daytona beach', url:'https://daytona.craigslist.org'},
    { name: 'florida keys', url:'https://keys.craigslist.org'},
    { name: 'fort lauderdale', url:'https://miami.craigslist.org'},
    { name: 'ft myers / SW florida', url:'https://fortmyers.craigslist.org'},
    { name: 'gainesville', url:'https://gainesville.craigslist.org'},
    { name: 'heartland florida', url:'https://cfl.craigslist.org'},
    { name: 'jacksonville', url:'https://jacksonville.craigslist.org'},
    { name: 'lakeland', url:'https://lakeland.craigslist.org'},
    { name: 'miami / dade', url:'https://miami.craigslist.org'},
    { name: 'north central FL', url:'https://lakecity.craigslist.org'},
    { name: 'ocala', url:'https://ocala.craigslist.org'},
    { name: 'okaloosa / walton', url:'https://okaloosa.craigslist.org'},
    { name: 'orlando', url:'https://orlando.craigslist.org'},
    { name: 'panama city', url:'https://panamacity.craigslist.org'},
    { name: 'pensacola', url:'https://pensacola.craigslist.org'},
    { name: 'sarasota-bradenton', url:'https://sarasota.craigslist.org'},
    { name: 'south florida', url:'https://miami.craigslist.org'},
    { name: 'space coast', url:'https://spacecoast.craigslist.org'},
    { name: 'st augustine', url:'https://staugustine.craigslist.org'},
    { name: 'tallahassee', url:'https://tallahassee.craigslist.org'},
    { name: 'tampa bay area', url:'https://tampa.craigslist.org'},
    { name: 'treasure coast', url:'https://treasure.craigslist.org'},
    { name: 'palm beach county', url:'https://miami.craigslist.org'},
    { name: 'albany', url:'https://albanyga.craigslist.org'},
    { name: 'athens', url:'https://athensga.craigslist.org'},
    { name: 'atlanta', url:'https://atlanta.craigslist.org'},
    { name: 'augusta', url:'https://augusta.craigslist.org'},
    { name: 'brunswick', url:'https://brunswick.craigslist.org'},
    { name: 'columbus', url:'https://columbusga.craigslist.org'},
    { name: 'macon / warner robins', url:'https://macon.craigslist.org'},
    { name: 'northwest GA', url:'https://nwga.craigslist.org'},
    { name: 'savannah / hinesville', url:'https://savannah.craigslist.org'},
    { name: 'statesboro', url:'https://statesboro.craigslist.org'},
    { name: 'valdosta', url:'https://valdosta.craigslist.org'},
    { name: 'hawaii', url:'https://honolulu.craigslist.org'},
    { name: 'boise', url:'https://boise.craigslist.org'},
    { name: 'east idaho', url:'https://eastidaho.craigslist.org'},
    { name: 'lewiston / clarkston', url:'https://lewiston.craigslist.org'},
    { name: 'twin falls', url:'https://twinfalls.craigslist.org'},
    { name: 'bloomington-normal', url:'https://bn.craigslist.org'},
    { name: 'champaign urbana', url:'https://chambana.craigslist.org'},
    { name: 'chicago', url:'https://chicago.craigslist.org'},
    { name: 'decatur', url:'https://decatur.craigslist.org'},
    { name: 'la salle co', url:'https://lasalle.craigslist.org'},
    { name: 'mattoon-charleston', url:'https://mattoon.craigslist.org'},
    { name: 'peoria', url:'https://peoria.craigslist.org'},
    { name: 'rockford', url:'https://rockford.craigslist.org'},
    { name: 'southern illinois', url:'https://carbondale.craigslist.org'},
    { name: 'springfield', url:'https://springfieldil.craigslist.org'},
    { name: 'western IL', url:'https://quincy.craigslist.org'},
    { name: 'bloomington', url:'https://bloomington.craigslist.org'},
    { name: 'evansville', url:'https://evansville.craigslist.org'},
    { name: 'fort wayne', url:'https://fortwayne.craigslist.org'},
    { name: 'indianapolis', url:'https://indianapolis.craigslist.org'},
    { name: 'kokomo', url:'https://kokomo.craigslist.org'},
    { name: 'lafayette / west lafayette', url:'https://tippecanoe.craigslist.org'},
    { name: 'muncie / anderson', url:'https://muncie.craigslist.org'},
    { name: 'richmond', url:'https://richmondin.craigslist.org'},
    { name: 'south bend / michiana', url:'https://southbend.craigslist.org'},
    { name: 'terre haute', url:'https://terrehaute.craigslist.org'},
    { name: 'ames', url:'https://ames.craigslist.org'},
    { name: 'cedar rapids', url:'https://cedarrapids.craigslist.org'},
    { name: 'des moines', url:'https://desmoines.craigslist.org'},
    { name: 'dubuque', url:'https://dubuque.craigslist.org'},
    { name: 'fort dodge', url:'https://fortdodge.craigslist.org'},
    { name: 'iowa city', url:'https://iowacity.craigslist.org'},
    { name: 'mason city', url:'https://masoncity.craigslist.org'},
    { name: 'quad cities', url:'https://quadcities.craigslist.org'},
    { name: 'sioux city', url:'https://siouxcity.craigslist.org'},
    { name: 'southeast IA', url:'https://ottumwa.craigslist.org'},
    { name: 'waterloo / cedar falls', url:'https://waterloo.craigslist.org'},
    { name: 'lawrence', url:'https://lawrence.craigslist.org'},
    { name: 'manhattan', url:'https://ksu.craigslist.org'},
    { name: 'northwest KS', url:'https://nwks.craigslist.org'},
    { name: 'salina', url:'https://salina.craigslist.org'},
    { name: 'southeast KS', url:'https://seks.craigslist.org'},
    { name: 'southwest KS', url:'https://swks.craigslist.org'},
    { name: 'topeka', url:'https://topeka.craigslist.org'},
    { name: 'wichita', url:'https://wichita.craigslist.org'},
    { name: 'bowling green', url:'https://bgky.craigslist.org'},
    { name: 'eastern kentucky', url:'https://eastky.craigslist.org'},
    { name: 'lexington', url:'https://lexington.craigslist.org'},
    { name: 'louisville', url:'https://louisville.craigslist.org'},
    { name: 'owensboro', url:'https://owensboro.craigslist.org'},
    { name: 'western KY', url:'https://westky.craigslist.org'},
    { name: 'baton rouge', url:'https://batonrouge.craigslist.org'},
    { name: 'central louisiana', url:'https://cenla.craigslist.org'},
    { name: 'houma', url:'https://houma.craigslist.org'},
    { name: 'lafayette', url:'https://lafayette.craigslist.org'},
    { name: 'lake charles', url:'https://lakecharles.craigslist.org'},
    { name: 'monroe', url:'https://monroe.craigslist.org'},
    { name: 'new orleans', url:'https://neworleans.craigslist.org'},
    { name: 'shreveport', url:'https://shreveport.craigslist.org'},
    { name: 'maine', url:'https://maine.craigslist.org'},
    { name: 'annapolis', url:'https://annapolis.craigslist.org'},
    { name: 'baltimore', url:'https://baltimore.craigslist.org'},
    { name: 'eastern shore', url:'https://easternshore.craigslist.org'},
    { name: 'frederick', url:'https://frederick.craigslist.org'},
    { name: 'southern maryland', url:'https://smd.craigslist.org'},
    { name: 'western maryland', url:'https://westmd.craigslist.org'},
    { name: 'boston', url:'https://boston.craigslist.org'},
    { name: 'cape cod / islands', url:'https://capecod.craigslist.org'},
    { name: 'south coast', url:'https://southcoast.craigslist.org'},
    { name: 'western massachusetts', url:'https://westernmass.craigslist.org'},
    { name: 'worcester / central MA', url:'https://worcester.craigslist.org'},
    { name: 'ann arbor', url:'https://annarbor.craigslist.org'},
    { name: 'battle creek', url:'https://battlecreek.craigslist.org'},
    { name: 'central michigan', url:'https://centralmich.craigslist.org'},
    { name: 'detroit metro', url:'https://detroit.craigslist.org'},
    { name: 'flint', url:'https://flint.craigslist.org'},
    { name: 'grand rapids', url:'https://grandrapids.craigslist.org'},
    { name: 'holland', url:'https://holland.craigslist.org'},
    { name: 'jackson', url:'https://jxn.craigslist.org'},
    { name: 'kalamazoo', url:'https://kalamazoo.craigslist.org'},
    { name: 'lansing', url:'https://lansing.craigslist.org'},
    { name: 'monroe', url:'https://monroemi.craigslist.org'},
    { name: 'muskegon', url:'https://muskegon.craigslist.org'},
    { name: 'northern michigan', url:'https://nmi.craigslist.org'},
    { name: 'port huron', url:'https://porthuron.craigslist.org'},
    { name: 'saginaw-midland-baycity', url:'https://saginaw.craigslist.org'},
    { name: 'southwest michigan', url:'https://swmi.craigslist.org'},
    { name: 'the thumb', url:'https://thumb.craigslist.org'},
    { name: 'upper peninsula', url:'https://up.craigslist.org'},
    { name: 'bemidji', url:'https://bemidji.craigslist.org'},
    { name: 'brainerd', url:'https://brainerd.craigslist.org'},
    { name: 'duluth / superior', url:'https://duluth.craigslist.org'},
    { name: 'mankato', url:'https://mankato.craigslist.org'},
    { name: 'minneapolis / st paul', url:'https://minneapolis.craigslist.org'},
    { name: 'rochester', url:'https://rmn.craigslist.org'},
    { name: 'southwest MN', url:'https://marshall.craigslist.org'},
    { name: 'st cloud', url:'https://stcloud.craigslist.org'},
    { name: 'gulfport / biloxi', url:'https://gulfport.craigslist.org'},
    { name: 'hattiesburg', url:'https://hattiesburg.craigslist.org'},
    { name: 'jackson', url:'https://jackson.craigslist.org'},
    { name: 'meridian', url:'https://meridian.craigslist.org'},
    { name: 'north mississippi', url:'https://northmiss.craigslist.org'},
    { name: 'southwest MS', url:'https://natchez.craigslist.org'},
    { name: 'columbia / jeff city', url:'https://columbiamo.craigslist.org'},
    { name: 'joplin', url:'https://joplin.craigslist.org'},
    { name: 'kansas city', url:'https://kansascity.craigslist.org'},
    { name: 'kirksville', url:'https://kirksville.craigslist.org'},
    { name: 'lake of the ozarks', url:'https://loz.craigslist.org'},
    { name: 'southeast missouri', url:'https://semo.craigslist.org'},
    { name: 'springfield', url:'https://springfield.craigslist.org'},
    { name: 'st joseph', url:'https://stjoseph.craigslist.org'},
    { name: 'st louis', url:'https://stlouis.craigslist.org'},
    { name: 'billings', url:'https://billings.craigslist.org'},
    { name: 'bozeman', url:'https://bozeman.craigslist.org'},
    { name: 'butte', url:'https://butte.craigslist.org'},
    { name: 'great falls', url:'https://greatfalls.craigslist.org'},
    { name: 'helena', url:'https://helena.craigslist.org'},
    { name: 'kalispell', url:'https://kalispell.craigslist.org'},
    { name: 'missoula', url:'https://missoula.craigslist.org'},
    { name: 'eastern montana', url:'https://montana.craigslist.org'},
    { name: 'grand island', url:'https://grandisland.craigslist.org'},
    { name: 'lincoln', url:'https://lincoln.craigslist.org'},
    { name: 'north platte', url:'https://northplatte.craigslist.org'},
    { name: 'omaha / council bluffs', url:'https://omaha.craigslist.org'},
    { name: 'scottsbluff / panhandle', url:'https://scottsbluff.craigslist.org'},
    { name: 'elko', url:'https://elko.craigslist.org'},
    { name: 'las vegas', url:'https://lasvegas.craigslist.org'},
    { name: 'reno / tahoe', url:'https://reno.craigslist.org'},
    { name: 'new hampshire', url:'https://nh.craigslist.org'},
    { name: 'central NJ', url:'https://cnj.craigslist.org'},
    { name: 'jersey shore', url:'https://jerseyshore.craigslist.org'},
    { name: 'north jersey', url:'https://newjersey.craigslist.org'},
    { name: 'south jersey', url:'https://southjersey.craigslist.org'},
    { name: 'albuquerque', url:'https://albuquerque.craigslist.org'},
    { name: 'clovis / portales', url:'https://clovis.craigslist.org'},
    { name: 'farmington', url:'https://farmington.craigslist.org'},
    { name: 'las cruces', url:'https://lascruces.craigslist.org'},
    { name: 'roswell / carlsbad', url:'https://roswell.craigslist.org'},
    { name: 'santa fe / taos', url:'https://santafe.craigslist.org'},
    { name: 'albany', url:'https://albany.craigslist.org'},
    { name: 'binghamton', url:'https://binghamton.craigslist.org'},
    { name: 'buffalo', url:'https://buffalo.craigslist.org'},
    { name: 'catskills', url:'https://catskills.craigslist.org'},
    { name: 'chautauqua', url:'https://chautauqua.craigslist.org'},
    { name: 'elmira-corning', url:'https://elmira.craigslist.org'},
    { name: 'finger lakes', url:'https://fingerlakes.craigslist.org'},
    { name: 'glens falls', url:'https://glensfalls.craigslist.org'},
    { name: 'hudson valley', url:'https://hudsonvalley.craigslist.org'},
    { name: 'ithaca', url:'https://ithaca.craigslist.org'},
    { name: 'long island', url:'https://longisland.craigslist.org'},
    { name: 'new york city', url:'https://newyork.craigslist.org'},
    { name: 'oneonta', url:'https://oneonta.craigslist.org'},
    { name: 'plattsburgh-adirondacks', url:'https://plattsburgh.craigslist.org'},
    { name: 'potsdam-canton-massena', url:'https://potsdam.craigslist.org'},
    { name: 'rochester', url:'https://rochester.craigslist.org'},
    { name: 'syracuse', url:'https://syracuse.craigslist.org'},
    { name: 'twin tiers NY/PA', url:'https://twintiers.craigslist.org'},
    { name: 'utica-rome-oneida', url:'https://utica.craigslist.org'},
    { name: 'watertown', url:'https://watertown.craigslist.org'},
    { name: 'asheville', url:'https://asheville.craigslist.org'},
    { name: 'boone', url:'https://boone.craigslist.org'},
    { name: 'charlotte', url:'https://charlotte.craigslist.org'},
    { name: 'eastern NC', url:'https://eastnc.craigslist.org'},
    { name: 'fayetteville', url:'https://fayetteville.craigslist.org'},
    { name: 'greensboro', url:'https://greensboro.craigslist.org'},
    { name: 'hickory / lenoir', url:'https://hickory.craigslist.org'},
    { name: 'jacksonville', url:'https://onslow.craigslist.org'},
    { name: 'outer banks', url:'https://outerbanks.craigslist.org'},
    { name: 'raleigh / durham / CH', url:'https://raleigh.craigslist.org'},
    { name: 'wilmington', url:'https://wilmington.craigslist.org'},
    { name: 'winston-salem', url:'https://winstonsalem.craigslist.org'},
    { name: 'bismarck', url:'https://bismarck.craigslist.org'},
    { name: 'fargo / moorhead', url:'https://fargo.craigslist.org'},
    { name: 'grand forks', url:'https://grandforks.craigslist.org'},
    { name: 'north dakota', url:'https://nd.craigslist.org'},
    { name: 'akron / canton', url:'https://akroncanton.craigslist.org'},
    { name: 'ashtabula', url:'https://ashtabula.craigslist.org'},
    { name: 'athens', url:'https://athensohio.craigslist.org'},
    { name: 'chillicothe', url:'https://chillicothe.craigslist.org'},
    { name: 'cincinnati', url:'https://cincinnati.craigslist.org'},
    { name: 'cleveland', url:'https://cleveland.craigslist.org'},
    { name: 'columbus', url:'https://columbus.craigslist.org'},
    { name: 'dayton / springfield', url:'https://dayton.craigslist.org'},
    { name: 'lima / findlay', url:'https://limaohio.craigslist.org'},
    { name: 'mansfield', url:'https://mansfield.craigslist.org'},
    { name: 'sandusky', url:'https://sandusky.craigslist.org'},
    { name: 'toledo', url:'https://toledo.craigslist.org'},
    { name: 'tuscarawas co', url:'https://tuscarawas.craigslist.org'},
    { name: 'youngstown', url:'https://youngstown.craigslist.org'},
    { name: 'zanesville / cambridge', url:'https://zanesville.craigslist.org'},
    { name: 'lawton', url:'https://lawton.craigslist.org'},
    { name: 'northwest OK', url:'https://enid.craigslist.org'},
    { name: 'oklahoma city', url:'https://oklahomacity.craigslist.org'},
    { name: 'stillwater', url:'https://stillwater.craigslist.org'},
    { name: 'tulsa', url:'https://tulsa.craigslist.org'},
    { name: 'bend', url:'https://bend.craigslist.org'},
    { name: 'corvallis/albany', url:'https://corvallis.craigslist.org'},
    { name: 'east oregon', url:'https://eastoregon.craigslist.org'},
    { name: 'eugene', url:'https://eugene.craigslist.org'},
    { name: 'klamath falls', url:'https://klamath.craigslist.org'},
    { name: 'medford-ashland', url:'https://medford.craigslist.org'},
    { name: 'oregon coast', url:'https://oregoncoast.craigslist.org'},
    { name: 'portland', url:'https://portland.craigslist.org'},
    { name: 'roseburg', url:'https://roseburg.craigslist.org'},
    { name: 'salem', url:'https://salem.craigslist.org'},
    { name: 'altoona-johnstown', url:'https://altoona.craigslist.org'},
    { name: 'cumberland valley', url:'https://chambersburg.craigslist.org'},
    { name: 'erie', url:'https://erie.craigslist.org'},
    { name: 'harrisburg', url:'https://harrisburg.craigslist.org'},
    { name: 'lancaster', url:'https://lancaster.craigslist.org'},
    { name: 'lehigh valley', url:'https://allentown.craigslist.org'},
    { name: 'meadville', url:'https://meadville.craigslist.org'},
    { name: 'philadelphia', url:'https://philadelphia.craigslist.org'},
    { name: 'pittsburgh', url:'https://pittsburgh.craigslist.org'},
    { name: 'poconos', url:'https://poconos.craigslist.org'},
    { name: 'reading', url:'https://reading.craigslist.org'},
    { name: 'scranton / wilkes-barre', url:'https://scranton.craigslist.org'},
    { name: 'state college', url:'https://pennstate.craigslist.org'},
    { name: 'williamsport', url:'https://williamsport.craigslist.org'},
    { name: 'york', url:'https://york.craigslist.org'},
    { name: 'rhode island', url:'https://providence.craigslist.org'},
    { name: 'charleston', url:'https://charleston.craigslist.org'},
    { name: 'columbia', url:'https://columbia.craigslist.org'},
    { name: 'florence', url:'https://florencesc.craigslist.org'},
    { name: 'greenville / upstate', url:'https://greenville.craigslist.org'},
    { name: 'hilton head', url:'https://hiltonhead.craigslist.org'},
    { name: 'myrtle beach', url:'https://myrtlebeach.craigslist.org'},
    { name: 'northeast SD', url:'https://nesd.craigslist.org'},
    { name: 'pierre / central SD', url:'https://csd.craigslist.org'},
    { name: 'rapid city / west SD', url:'https://rapidcity.craigslist.org'},
    { name: 'sioux falls / SE SD', url:'https://siouxfalls.craigslist.org'},
    { name: 'south dakota', url:'https://sd.craigslist.org'},
    { name: 'chattanooga', url:'https://chattanooga.craigslist.org'},
    { name: 'clarksville', url:'https://clarksville.craigslist.org'},
    { name: 'cookeville', url:'https://cookeville.craigslist.org'},
    { name: 'jackson', url:'https://jacksontn.craigslist.org'},
    { name: 'knoxville', url:'https://knoxville.craigslist.org'},
    { name: 'memphis', url:'https://memphis.craigslist.org'},
    { name: 'nashville', url:'https://nashville.craigslist.org'},
    { name: 'tri-cities', url:'https://tricities.craigslist.org'},
    { name: 'abilene', url:'https://abilene.craigslist.org'},
    { name: 'amarillo', url:'https://amarillo.craigslist.org'},
    { name: 'austin', url:'https://austin.craigslist.org'},
    { name: 'beaumont / port arthur', url:'https://beaumont.craigslist.org'},
    { name: 'brownsville', url:'https://brownsville.craigslist.org'},
    { name: 'college station', url:'https://collegestation.craigslist.org'},
    { name: 'corpus christi', url:'https://corpuschristi.craigslist.org'},
    { name: 'dallas / fort worth', url:'https://dallas.craigslist.org'},
    { name: 'deep east texas', url:'https://nacogdoches.craigslist.org'},
    { name: 'del rio / eagle pass', url:'https://delrio.craigslist.org'},
    { name: 'el paso', url:'https://elpaso.craigslist.org'},
    { name: 'galveston', url:'https://galveston.craigslist.org'},
    { name: 'houston', url:'https://houston.craigslist.org'},
    { name: 'killeen / temple / ft hood', url:'https://killeen.craigslist.org'},
    { name: 'laredo', url:'https://laredo.craigslist.org'},
    { name: 'lubbock', url:'https://lubbock.craigslist.org'},
    { name: 'mcallen / edinburg', url:'https://mcallen.craigslist.org'},
    { name: 'odessa / midland', url:'https://odessa.craigslist.org'},
    { name: 'san angelo', url:'https://sanangelo.craigslist.org'},
    { name: 'san antonio', url:'https://sanantonio.craigslist.org'},
    { name: 'san marcos', url:'https://sanmarcos.craigslist.org'},
    { name: 'southwest TX', url:'https://bigbend.craigslist.org'},
    { name: 'texoma', url:'https://texoma.craigslist.org'},
    { name: 'tyler / east TX', url:'https://easttexas.craigslist.org'},
    { name: 'victoria', url:'https://victoriatx.craigslist.org'},
    { name: 'waco', url:'https://waco.craigslist.org'},
    { name: 'wichita falls', url:'https://wichitafalls.craigslist.org'},
    { name: 'logan', url:'https://logan.craigslist.org'},
    { name: 'ogden-clearfield', url:'https://ogden.craigslist.org'},
    { name: 'provo / orem', url:'https://provo.craigslist.org'},
    { name: 'salt lake city', url:'https://saltlakecity.craigslist.org'},
    { name: 'st george', url:'https://stgeorge.craigslist.org'},
    { name: 'vermont', url:'https://vermont.craigslist.org'},
    { name: 'charlottesville', url:'https://charlottesville.craigslist.org'},
    { name: 'danville', url:'https://danville.craigslist.org'},
    { name: 'fredericksburg', url:'https://fredericksburg.craigslist.org'},
    { name: 'hampton roads', url:'https://norfolk.craigslist.org'},
    { name: 'harrisonburg', url:'https://harrisonburg.craigslist.org'},
    { name: 'lynchburg', url:'https://lynchburg.craigslist.org'},
    { name: 'new river valley', url:'https://blacksburg.craigslist.org'},
    { name: 'richmond', url:'https://richmond.craigslist.org'},
    { name: 'roanoke', url:'https://roanoke.craigslist.org'},
    { name: 'southwest VA', url:'https://swva.craigslist.org'},
    { name: 'winchester', url:'https://winchester.craigslist.org'},
    { name: 'bellingham', url:'https://bellingham.craigslist.org'},
    { name: 'kennewick-pasco-richland', url:'https://kpr.craigslist.org'},
    { name: 'moses lake', url:'https://moseslake.craigslist.org'},
    { name: 'olympic peninsula', url:'https://olympic.craigslist.org'},
    { name: 'pullman / moscow', url:'https://pullman.craigslist.org'},
    { name: 'seattle-tacoma', url:'https://seattle.craigslist.org'},
    { name: 'skagit / island / SJI', url:'https://skagit.craigslist.org'},
    { name: 'spokane / coeur d alene', url:'https://spokane.craigslist.org'},
    { name: 'wenatchee', url:'https://wenatchee.craigslist.org'},
    { name: 'yakima', url:'https://yakima.craigslist.org'},
    { name: 'charleston', url:'https://charlestonwv.craigslist.org'},
    { name: 'eastern panhandle', url:'https://martinsburg.craigslist.org'},
    { name: 'huntington-ashland', url:'https://huntington.craigslist.org'},
    { name: 'morgantown', url:'https://morgantown.craigslist.org'},
    { name: 'northern panhandle', url:'https://wheeling.craigslist.org'},
    { name: 'parkersburg-marietta', url:'https://parkersburg.craigslist.org'},
    { name: 'southern WV', url:'https://swv.craigslist.org'},
    { name: 'west virginia (old)', url:'https://wv.craigslist.org'},
    { name: 'appleton-oshkosh-FDL', url:'https://appleton.craigslist.org'},
    { name: 'eau claire', url:'https://eauclaire.craigslist.org'},
    { name: 'green bay', url:'https://greenbay.craigslist.org'},
    { name: 'janesville', url:'https://janesville.craigslist.org'},
    { name: 'kenosha-racine', url:'https://racine.craigslist.org'},
    { name: 'la crosse', url:'https://lacrosse.craigslist.org'},
    { name: 'madison', url:'https://madison.craigslist.org'},
    { name: 'milwaukee', url:'https://milwaukee.craigslist.org'},
    { name: 'northern WI', url:'https://northernwi.craigslist.org'},
    { name: 'sheboygan', url:'https://sheboygan.craigslist.org'},
    { name: 'wausau', url:'https://wausau.craigslist.org'},
    { name: 'wyoming', url:'https://wyoming.craigslist.org'},
    { name: 'guam-micronesia', url:'https://micronesia.craigslist.org'},
    { name: 'puerto rico', url:'https://puertorico.craigslist.org'},
    { name: 'U.S. virgin islands', url:'https://virgin.craigslist.org'},
    { name: 'calgary', url:'https://calgary.craigslist.org'},
    { name: 'edmonton', url:'https://edmonton.craigslist.org'},
    { name: 'ft mcmurray', url:'https://ftmcmurray.craigslist.org'},
    { name: 'lethbridge', url:'https://lethbridge.craigslist.org'},
    { name: 'medicine hat', url:'https://hat.craigslist.org'},
    { name: 'peace river country', url:'https://peace.craigslist.org'},
    { name: 'red deer', url:'https://reddeer.craigslist.org'},
    { name: 'cariboo', url:'https://cariboo.craigslist.org'},
    { name: 'comox valley', url:'https://comoxvalley.craigslist.org'},
    { name: 'fraser valley', url:'https://abbotsford.craigslist.org'},
    { name: 'kamloops', url:'https://kamloops.craigslist.org'},
    { name: 'kelowna / okanagan', url:'https://kelowna.craigslist.org'},
    { name: 'kootenays', url:'https://kootenays.craigslist.org'},
    { name: 'nanaimo', url:'https://nanaimo.craigslist.org'},
    { name: 'prince george', url:'https://princegeorge.craigslist.org'},
    { name: 'skeena-bulkley', url:'https://skeena.craigslist.org'},
    { name: 'sunshine coast', url:'https://sunshine.craigslist.org'},
    { name: 'vancouver', url:'https://vancouver.craigslist.org'},
    { name: 'victoria', url:'https://victoria.craigslist.org'},
    { name: 'whistler', url:'https://whistler.craigslist.org'},
    { name: 'winnipeg', url:'https://winnipeg.craigslist.org'},
    { name: 'new brunswick', url:'https://newbrunswick.craigslist.org'},
    { name: "st john's", url:'https://newfoundland.craigslist.org'},
    { name: 'territories', url:'https://territories.craigslist.org'},
    { name: 'yellowknife', url:'https://yellowknife.craigslist.org'},
    { name: 'halifax', url:'https://halifax.craigslist.org'},
    { name: 'barrie', url:'https://barrie.craigslist.org'},
    { name: 'belleville', url:'https://belleville.craigslist.org'},
    { name: 'brantford-woodstock', url:'https://brantford.craigslist.org'},
    { name: 'chatham-kent', url:'https://chatham.craigslist.org'},
    { name: 'cornwall', url:'https://cornwall.craigslist.org'},
    { name: 'guelph', url:'https://guelph.craigslist.org'},
    { name: 'hamilton-burlington', url:'https://hamilton.craigslist.org'},
    { name: 'kingston', url:'https://kingston.craigslist.org'},
    { name: 'kitchener-waterloo-cambridge', url:'https://kitchener.craigslist.org'},
    { name: 'london', url:'https://londonon.craigslist.org'},
    { name: 'niagara region', url:'https://niagara.craigslist.org'},
    { name: 'ottawa-hull-gatineau', url:'https://ottawa.craigslist.org'},
    { name: 'owen sound', url:'https://owensound.craigslist.org'},
    { name: 'peterborough', url:'https://peterborough.craigslist.org'},
    { name: 'sarnia', url:'https://sarnia.craigslist.org'},
    { name: 'sault ste marie', url:'https://soo.craigslist.org'},
    { name: 'sudbury', url:'https://sudbury.craigslist.org'},
    { name: 'thunder bay', url:'https://thunderbay.craigslist.org'},
    { name: 'toronto', url:'https://toronto.craigslist.org'},
    { name: 'windsor', url:'https://windsor.craigslist.org'},
    { name: 'prince edward island', url:'https://pei.craigslist.org'},
    { name: 'montreal', url:'https://montreal.craigslist.org'},
    { name: 'quebec city', url:'https://quebec.craigslist.org'},
    { name: 'saguenay', url:'https://saguenay.craigslist.org'},
    { name: 'sherbrooke', url:'https://sherbrooke.craigslist.org'},
    { name: 'trois-rivieres', url:'https://troisrivieres.craigslist.org'},
    { name: 'regina', url:'https://regina.craigslist.org'},
    { name: 'saskatoon', url:'https://saskatoon.craigslist.org'},
    { name: 'whitehorse', url:'https://whitehorse.craigslist.org'},
    { name: 'vienna', url:'https://vienna.craigslist.org'},
    { name: 'belgium', url:'https://brussels.craigslist.org'},
    { name: 'bulgaria', url:'https://bulgaria.craigslist.org'},
    { name: 'croatia', url:'https://zagreb.craigslist.org'},
    { name: 'prague', url:'https://prague.craigslist.org'},
    { name: 'copenhagen', url:'https://copenhagen.craigslist.org'},
    { name: 'finland', url:'https://helsinki.craigslist.org'},
    { name: 'bordeaux', url:'https://bordeaux.craigslist.org'},
    { name: 'brittany', url:'https://rennes.craigslist.org'},
    { name: 'grenoble', url:'https://grenoble.craigslist.org'},
    { name: 'lille', url:'https://lille.craigslist.org'},
    { name: 'loire valley', url:'https://loire.craigslist.org'},
    { name: 'lyon', url:'https://lyon.craigslist.org'},
    { name: 'marseille', url:'https://marseilles.craigslist.org'},
    { name: 'montpellier', url:'https://montpellier.craigslist.org'},
    { name: "nice / cote d'azur", url:'https://cotedazur.craigslist.org'},
    { name: 'normandy', url:'https://rouen.craigslist.org'},
    { name: 'paris', url:'https://paris.craigslist.org'},
    { name: 'strasbourg', url:'https://strasbourg.craigslist.org'},
    { name: 'toulouse', url:'https://toulouse.craigslist.org'},
    { name: 'berlin', url:'https://berlin.craigslist.org'},
    { name: 'bremen', url:'https://bremen.craigslist.org'},
    { name: 'cologne', url:'https://cologne.craigslist.org'},
    { name: 'dresden', url:'https://dresden.craigslist.org'},
    { name: 'dusseldorf', url:'https://dusseldorf.craigslist.org'},
    { name: 'essen / ruhr', url:'https://essen.craigslist.org'},
    { name: 'frankfurt', url:'https://frankfurt.craigslist.org'},
    { name: 'hamburg', url:'https://hamburg.craigslist.org'},
    { name: 'hannover', url:'https://hannover.craigslist.org'},
    { name: 'heidelberg', url:'https://heidelberg.craigslist.org'},
    { name: 'kaiserslautern', url:'https://kaiserslautern.craigslist.org'},
    { name: 'leipzig', url:'https://leipzig.craigslist.org'},
    { name: 'munich', url:'https://munich.craigslist.org'},
    { name: 'nuremberg', url:'https://nuremberg.craigslist.org'},
    { name: 'stuttgart', url:'https://stuttgart.craigslist.org'},
    { name: 'greece', url:'https://athens.craigslist.org'},
    { name: 'budapest', url:'https://budapest.craigslist.org'},
    { name: 'reykjavik', url:'https://reykjavik.craigslist.org'},
    { name: 'dublin', url:'https://dublin.craigslist.org'},
    { name: 'bologna', url:'https://bologna.craigslist.org'},
    { name: 'florence / tuscany', url:'https://florence.craigslist.org'},
    { name: 'genoa', url:'https://genoa.craigslist.org'},
    { name: 'milan', url:'https://milan.craigslist.org'},
    { name: 'napoli / campania', url:'https://naples.craigslist.org'},
    { name: 'perugia', url:'https://perugia.craigslist.org'},
    { name: 'rome', url:'https://rome.craigslist.org'},
    { name: 'sardinia', url:'https://sardinia.craigslist.org'},
    { name: 'sicilia', url:'https://sicily.craigslist.org'},
    { name: 'torino', url:'https://torino.craigslist.org'},
    { name: 'venice / veneto', url:'https://venice.craigslist.org'},
    { name: 'luxembourg', url:'https://luxembourg.craigslist.org'},
    { name: 'amsterdam / randstad', url:'https://amsterdam.craigslist.org'},
    { name: 'norway', url:'https://oslo.craigslist.org'},
    { name: 'poland', url:'https://warsaw.craigslist.org'},
    { name: 'faro / algarve', url:'https://faro.craigslist.org'},
    { name: 'lisbon', url:'https://lisbon.craigslist.org'},
    { name: 'porto', url:'https://porto.craigslist.org'},
    { name: 'romania', url:'https://bucharest.craigslist.org'},
    { name: 'moscow', url:'https://moscow.craigslist.org'},
    { name: 'st petersburg', url:'https://stpetersburg.craigslist.org'},
    { name: 'alicante', url:'https://alicante.craigslist.org'},
    { name: 'baleares', url:'https://baleares.craigslist.org'},
    { name: 'barcelona', url:'https://barcelona.craigslist.org'},
    { name: 'bilbao', url:'https://bilbao.craigslist.org'},
    { name: 'cadiz', url:'https://cadiz.craigslist.org'},
    { name: 'canarias', url:'https://canarias.craigslist.org'},
    { name: 'granada', url:'https://granada.craigslist.org'},
    { name: 'madrid', url:'https://madrid.craigslist.org'},
    { name: 'malaga', url:'https://malaga.craigslist.org'},
    { name: 'sevilla', url:'https://sevilla.craigslist.org'},
    { name: 'valencia', url:'https://valencia.craigslist.org'},
    { name: 'sweden', url:'https://stockholm.craigslist.org'},
    { name: 'basel', url:'https://basel.craigslist.org'},
    { name: 'bern', url:'https://bern.craigslist.org'},
    { name: 'geneva', url:'https://geneva.craigslist.org'},
    { name: 'lausanne', url:'https://lausanne.craigslist.org'},
    { name: 'zurich', url:'https://zurich.craigslist.org'},
    { name: 'turkey', url:'https://istanbul.craigslist.org'},
    { name: 'ukraine', url:'https://ukraine.craigslist.org'},
    { name: 'aberdeen', url:'https://aberdeen.craigslist.org'},
    { name: 'bath', url:'https://bath.craigslist.org'},
    { name: 'belfast', url:'https://belfast.craigslist.org'},
    { name: 'birmingham / west mids', url:'https://birmingham.craigslist.org'},
    { name: 'brighton', url:'https://brighton.craigslist.org'},
    { name: 'bristol', url:'https://bristol.craigslist.org'},
    { name: 'cambridge, UK', url:'https://cambridge.craigslist.org'},
    { name: 'cardiff / wales', url:'https://cardiff.craigslist.org'},
    { name: 'coventry', url:'https://coventry.craigslist.org'},
    { name: 'derby', url:'https://derby.craigslist.org'},
    { name: 'devon', url:'https://devon.craigslist.org'},
    { name: 'dundee', url:'https://dundee.craigslist.org'},
    { name: 'east anglia', url:'https://norwich.craigslist.org'},
    { name: 'east midlands', url:'https://eastmids.craigslist.org'},
    { name: 'edinburgh', url:'https://edinburgh.craigslist.org'},
    { name: 'essex', url:'https://essex.craigslist.org'},
    { name: 'glasgow', url:'https://glasgow.craigslist.org'},
    { name: 'hampshire', url:'https://hampshire.craigslist.org'},
    { name: 'kent', url:'https://kent.craigslist.org'},
    { name: 'leeds', url:'https://leeds.craigslist.org'},
    { name: 'liverpool', url:'https://liverpool.craigslist.org'},
    { name: 'london', url:'https://london.craigslist.org'},
    { name: 'manchester', url:'https://manchester.craigslist.org'},
    { name: 'newcastle / NE england', url:'https://newcastle.craigslist.org'},
    { name: 'nottingham', url:'https://nottingham.craigslist.org'},
    { name: 'oxford', url:'https://oxford.craigslist.org'},
    { name: 'sheffield', url:'https://sheffield.craigslist.org'},
    { name: 'bangladesh', url:'https://bangladesh.craigslist.org'},
    { name: 'beijing', url:'https://beijing.craigslist.org'},
    { name: 'chengdu', url:'https://chengdu.craigslist.org'},
    { name: 'chongqing', url:'https://chongqing.craigslist.org'},
    { name: 'dalian', url:'https://dalian.craigslist.org'},
    { name: 'guangzhou', url:'https://guangzhou.craigslist.org'},
    { name: 'hangzhou', url:'https://hangzhou.craigslist.org'},
    { name: 'nanjing', url:'https://nanjing.craigslist.org'},
    { name: 'shanghai', url:'https://shanghai.craigslist.org'},
    { name: 'shenyang', url:'https://shenyang.craigslist.org'},
    { name: 'shenzhen', url:'https://shenzhen.craigslist.org'},
    { name: 'wuhan', url:'https://wuhan.craigslist.org'},
    { name: "xi'an", url:'https://xian.craigslist.org'},
    { name: 'guam-micronesia', url:'https://micronesia.craigslist.org'},
    { name: 'hong kong', url:'https://hongkong.craigslist.org'},
    { name: 'ahmedabad', url:'https://ahmedabad.craigslist.org'},
    { name: 'bangalore', url:'https://bangalore.craigslist.org'},
    { name: 'bhubaneswar', url:'https://bhubaneswar.craigslist.org'},
    { name: 'chandigarh', url:'https://chandigarh.craigslist.org'},
    { name: 'chennai (madras)', url:'https://chennai.craigslist.org'},
    { name: 'delhi', url:'https://delhi.craigslist.org'},
    { name: 'goa', url:'https://goa.craigslist.org'},
    { name: 'hyderabad', url:'https://hyderabad.craigslist.org'},
    { name: 'indore', url:'https://indore.craigslist.org'},
    { name: 'jaipur', url:'https://jaipur.craigslist.org'},
    { name: 'kerala', url:'https://kerala.craigslist.org'},
    { name: 'kolkata (calcutta)', url:'https://kolkata.craigslist.org'},
    { name: 'lucknow', url:'https://lucknow.craigslist.org'},
    { name: 'mumbai', url:'https://mumbai.craigslist.org'},
    { name: 'pune', url:'https://pune.craigslist.org'},
    { name: 'surat surat', url:'https://surat.craigslist.org'},
    { name: 'indonesia', url:'https://jakarta.craigslist.org'},
    { name: 'iran', url:'https://tehran.craigslist.org'},
    { name: 'iraq', url:'https://baghdad.craigslist.org'},
    { name: 'haifa', url:'https://haifa.craigslist.org'},
    { name: 'jerusalem', url:'https://jerusalem.craigslist.org'},
    { name: 'tel aviv', url:'https://telaviv.craigslist.org'},
    { name: 'west bank', url:'https://ramallah.craigslist.org'},
    { name: 'fukuoka', url:'https://fukuoka.craigslist.org'},
    { name: 'hiroshima', url:'https://hiroshima.craigslist.org'},
    { name: 'nagoya', url:'https://nagoya.craigslist.org'},
    { name: 'okinawa', url:'https://okinawa.craigslist.org'},
    { name: 'osaka-kobe-kyoto', url:'https://osaka.craigslist.org'},
    { name: 'sapporo', url:'https://sapporo.craigslist.org'},
    { name: 'sendai', url:'https://sendai.craigslist.org'},
    { name: 'tokyo', url:'https://tokyo.craigslist.org'},
    { name: 'seoul', url:'https://seoul.craigslist.org'},
    { name: 'kuwait', url:'https://kuwait.craigslist.org'},
    { name: 'beirut, lebanon', url:'https://beirut.craigslist.org'},
    { name: 'malaysia', url:'https://malaysia.craigslist.org'},
    { name: 'pakistan', url:'https://pakistan.craigslist.org'},
    { name: 'bacolod', url:'https://bacolod.craigslist.org'},
    { name: 'bicol region', url:'https://naga.craigslist.org'},
    { name: 'cagayan de oro', url:'https://cdo.craigslist.org'},
    { name: 'cebu', url:'https://cebu.craigslist.org'},
    { name: 'davao city', url:'https://davaocity.craigslist.org'},
    { name: 'iloilo', url:'https://iloilo.craigslist.org'},
    { name: 'manila', url:'https://manila.craigslist.org'},
    { name: 'pampanga', url:'https://pampanga.craigslist.org'},
    { name: 'zamboanga', url:'https://zamboanga.craigslist.org'},
    { name: 'singapore', url:'https://singapore.craigslist.org'},
    { name: 'taiwan', url:'https://taipei.craigslist.org'},
    { name: 'united arab emirates', url:'https://dubai.craigslist.org'},
    { name: 'vietnam', url:'https://vietnam.craigslist.org'},
    { name: 'adelaide', url:'https://adelaide.craigslist.org'},
    { name: 'brisbane', url:'https://brisbane.craigslist.org'},
    { name: 'cairns', url:'https://cairns.craigslist.org'},
    { name: 'canberra', url:'https://canberra.craigslist.org'},
    { name: 'darwin', url:'https://darwin.craigslist.org'},
    { name: 'gold coast', url:'https://goldcoast.craigslist.org'},
    { name: 'melbourne', url:'https://melbourne.craigslist.org'},
    { name: 'newcastle, NSW', url:'https://ntl.craigslist.org'},
    { name: 'perth', url:'https://perth.craigslist.org'},
    { name: 'sydney', url:'https://sydney.craigslist.org'},
    { name: 'tasmania', url:'https://hobart.craigslist.org'},
    { name: 'wollongong', url:'https://wollongong.craigslist.org'},
    { name: 'auckland', url:'https://auckland.craigslist.org'},
    { name: 'christchurch', url:'https://christchurch.craigslist.org'},
    { name: 'dunedin', url:'https://dunedin.craigslist.org'},
    { name: 'wellington', url:'https://wellington.craigslist.org'},
    { name: 'buenos aires', url:'https://buenosaires.craigslist.org'},
    { name: 'bolivia', url:'https://lapaz.craigslist.org'},
    { name: 'belo horizonte', url:'https://belohorizonte.craigslist.org'},
    { name: 'brasilia', url:'https://brasilia.craigslist.org'},
    { name: 'curitiba', url:'https://curitiba.craigslist.org'},
    { name: 'fortaleza', url:'https://fortaleza.craigslist.org'},
    { name: 'porto alegre', url:'https://portoalegre.craigslist.org'},
    { name: 'recife', url:'https://recife.craigslist.org'},
    { name: 'rio de janeiro', url:'https://rio.craigslist.org'},
    { name: 'salvador, bahia', url:'https://salvador.craigslist.org'},
    { name: 'sao paulo', url:'https://saopaulo.craigslist.org'},
    { name: 'caribbean islands', url:'https://caribbean.craigslist.org'},
    { name: 'chile', url:'https://santiago.craigslist.org'},
    { name: 'colombia', url:'https://colombia.craigslist.org'},
    { name: 'costa rica', url:'https://costarica.craigslist.org'},
    { name: 'dominican republic', url:'https://santodomingo.craigslist.org'},
    { name: 'ecuador', url:'https://quito.craigslist.org'},
    { name: 'el salvador', url:'https://elsalvador.craigslist.org'},
    { name: 'guatemala', url:'https://guatemala.craigslist.org'},
    { name: 'acapulco', url:'https://acapulco.craigslist.org'},
    { name: 'baja california sur', url:'https://bajasur.craigslist.org'},
    { name: 'chihuahua', url:'https://chihuahua.craigslist.org'},
    { name: 'ciudad juarez', url:'https://juarez.craigslist.org'},
    { name: 'guadalajara', url:'https://guadalajara.craigslist.org'},
    { name: 'guanajuato', url:'https://guanajuato.craigslist.org'},
    { name: 'hermosillo', url:'https://hermosillo.craigslist.org'},
    { name: 'mazatlan', url:'https://mazatlan.craigslist.org'},
    { name: 'mexico city', url:'https://mexicocity.craigslist.org'},
    { name: 'monterrey', url:'https://monterrey.craigslist.org'},
    { name: 'oaxaca', url:'https://oaxaca.craigslist.org'},
    { name: 'puebla', url:'https://puebla.craigslist.org'},
    { name: 'puerto vallarta', url:'https://pv.craigslist.org'},
    { name: 'tijuana', url:'https://tijuana.craigslist.org'},
    { name: 'veracruz', url:'https://veracruz.craigslist.org'},
    { name: 'yucatan', url:'https://yucatan.craigslist.org'},
    { name: 'nicaragua', url:'https://managua.craigslist.org'},
    { name: 'panama', url:'https://panama.craigslist.org'},
    { name: 'peru', url:'https://lima.craigslist.org'},
    { name: 'puerto rico', url:'https://puertorico.craigslist.org'},
    { name: 'montevideo', url:'https://montevideo.craigslist.org'},
    { name: 'venezuela', url:'https://caracas.craigslist.org'},
    { name: 'virgin islands', url:'https://virgin.craigslist.org'},
    { name: 'egypt', url:'https://cairo.craigslist.org'},
    { name: 'ethiopia', url:'https://addisababa.craigslist.org'},
    { name: 'ghana', url:'https://accra.craigslist.org'},
    { name: 'kenya', url:'https://kenya.craigslist.org'},
    { name: 'morocco', url:'https://casablanca.craigslist.org'},
    { name: 'cape town', url:'https://capetown.craigslist.org'},
    { name: 'durban', url:'https://durban.craigslist.org'},
    { name: 'johannesburg', url:'https://johannesburg.craigslist.org'},
    { name: 'pretoria', url:'https://pretoria.craigslist.org'},
    { name: 'tunisia', url:'https://tunis.craigslist.org'},
    // Add more nations as needed
  ];

  // Function to filter nations based on user input
  function filterNations(event) {
    const searchValue = event.target.value.toLowerCase();
    const dropdown = document.getElementById('nationDropdown');
    dropdown.innerHTML = '';

    const filteredNations = nations.filter(nation => nation.name.toLowerCase().startsWith(searchValue));
    filteredNations.forEach(nation => {
      const item = document.createElement('div');
      item.textContent = nation.name;
      item.classList.add('dropdown-menu-item');
      item.onclick = () => {
        window.location.href = nation.url;
      };
      dropdown.appendChild(item);
    });
  }

var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}