 // List of nations with their corresponding URLs
 const nations = [
    { name: 'activities', url: 'craigslist.html' },
    { name: 'artists', url: 'craigslist.html' },
    { name: 'childcare', url: 'craigslist.html' },
    { name: 'classes', url: 'craigslist.html' },
    { name: 'events', url: 'craigslist.html' },
    { name: 'general', url: 'craigslist.html' },
    { name: 'groups', url: 'craigslist.html' },
    { name: 'local news', url: 'craigslist.html' },
    { name: 'lost+found', url: 'craigslist.html' },
    { name: 'missed connections', url: 'craigslist.html' },
    { name: 'musicians', url: 'craigslist.html' },
    { name: 'pets', url: 'craigslist.html' },
    { name: 'politics', url: 'craigslist.html' },
    { name: 'rants raves', url: 'craigslist.html' },
    { name: 'rideshare', url: 'craigslist.html' },
    { name: 'volunteers', url: 'craigslist.html' },
    { name: 'automotive', url: 'craigslist.html' },
    { name: 'beauty', url: 'craigslist.html' },
    { name: 'cell/mobile', url: 'craigslist.html' },
    { name: 'computer', url: 'craigslist.html' },
    { name: 'creative', url: 'craigslist.html' },
    { name: 'cycle', url: 'craigslist.html' },
    { name: 'event', url: 'craigslist.html' },
    { name: 'farm+garden', url: 'craigslist.html' },
    { name: 'financial', url: 'craigslist.html' },
    { name: 'health/well', url: 'craigslist.html' },
    { name: 'household', url: 'craigslist.html' },
    { name: 'labor/move', url: 'craigslist.html' },
    { name: 'legal', url: 'craigslist.html' },
    { name: 'lessons', url: 'craigslist.html' },
    { name: 'marine', url: 'craigslist.html' },
    { name: 'pet', url: 'craigslist.html' },
    { name: 'real estate', url: 'craigslist.html' },
    { name: 'skilled trade', url: 'craigslist.html' },
    { name: 'sm biz ads', url: 'craigslist.html' },
    { name: 'travel/vac', url: 'craigslist.html' },
    { name: 'write/ed/tran', url: 'craigslist.html' },
    { name: 'antiques', url: 'craigslist.html' },
    { name: 'appliances', url: 'craigslist.html' },
    { name: 'arts+crafts', url: 'craigslist.html' },
    { name: 'atv/utv/sno', url: 'craigslist.html' },
    { name: 'auto parts', url: 'craigslist.html' },
    { name: 'aviation', url: 'craigslist.html' },
    { name: 'baby+kid', url: 'craigslist.html' },
    { name: 'barter', url: 'craigslist.html' },
    { name: 'beauty+hlth', url: 'craigslist.html' },
    { name: 'bike parts', url: 'craigslist.html' },
    { name: 'bikes', url: 'craigslist.html' },
    { name: 'boat parts', url: 'craigslist.html' },
    { name: 'boats', url: 'craigslist.html' },
    { name: 'books', url: 'craigslist.html' },
    { name: 'business', url: 'craigslist.html' },
    { name: 'cars+trucks', url: 'craigslist.html' },
    { name: 'cds/dvd/vhs', url: 'craigslist.html' },
    { name: 'cell phones', url: 'craigslist.html' },
    { name: 'clothes+acc', url: 'craigslist.html' },
    { name: 'collectibles', url: 'craigslist.html' },
    { name: 'computer parts', url: 'craigslist.html' },
    { name: 'computers', url: 'craigslist.html' },
    { name: 'electronics', url: 'craigslist.html' },
    { name: 'farm+garden', url: 'craigslist.html' },
    { name: 'free', url: 'craigslist.html' },
    { name: 'furniture', url: 'craigslist.html' },
    { name: 'garage sale', url: 'craigslist.html' },
    { name: 'general', url: 'craigslist.html' },
    { name: 'heavy equip', url: 'craigslist.html' },
    { name: 'household', url: 'craigslist.html' },
    { name: 'jewelry', url: 'craigslist.html' },
    { name: 'materials', url: 'craigslist.html' },
    { name: 'motorcycle parts', url: 'craigslist.html' },
    { name: 'motorcycles', url: 'craigslist.html' },
    { name: 'music instr', url: 'craigslist.html' },
    { name: 'photo+video', url: 'craigslist.html' },
    { name: 'rvs+camp', url: 'craigslist.html' },
    { name: 'sporting', url: 'craigslist.html' },
    { name: 'tickets', url: 'craigslist.html' },
    { name: 'tools', url: 'craigslist.html' },
    { name: 'toys+games', url: 'craigslist.html' },
    { name: 'trailers', url: 'craigslist.html' },
    { name: 'video gaming', url: 'craigslist.html' },
    { name: 'wanted', url: 'craigslist.html' },
    { name: 'wheels+tires', url: 'craigslist.html' },
    { name: 'apple', url: 'craigslist.html' },
    { name: 'arts', url: 'craigslist.html' },
    { name: 'atheist', url: 'craigslist.html' },
    { name: 'autos', url: 'craigslist.html' },
    { name: 'beauty', url: 'craigslist.html' },
    { name: 'bikes', url: 'craigslist.html' },
    { name: 'celebs', url: 'craigslist.html' },
    { name: 'comp', url: 'craigslist.html' },
    { name: 'cosmos', url: 'craigslist.html' },
    { name: 'diet', url: 'craigslist.html' },
    { name: 'divorce', url: 'craigslist.html' },
    { name: 'dying', url: 'craigslist.html' },
    { name: 'eco', url: 'craigslist.html' },
    { name: 'feedbk', url: 'craigslist.html' },
    { name: 'film', url: 'craigslist.html' },
    { name: 'fixit', url: 'craigslist.html' },
    { name: 'food', url: 'craigslist.html' },
    { name: 'frugal', url: 'craigslist.html' },
    { name: 'gaming', url: 'craigslist.html' },
    { name: 'garden', url: 'craigslist.html' },
    { name: 'haiku', url: 'craigslist.html' },
    { name: 'help', url: 'craigslist.html' },
    { name: 'history', url: 'craigslist.html' },
    { name: 'housing', url: 'craigslist.html' },
    { name: 'jobs', url: 'craigslist.html' },
    { name: 'jokes', url: 'craigslist.html' },
    { name: 'legal', url: 'craigslist.html' },
    { name: 'manners', url: 'craigslist.html' },
    { name: 'marriage', url: 'craigslist.html' },
    { name: 'money', url: 'craigslist.html' },
    { name: 'music', url: 'craigslist.html' },
    { name: 'open', url: 'craigslist.html' },
    { name: 'parent', url: 'craigslist.html' },
    { name: 'pets', url: 'craigslist.html' },
    { name: 'philos', url: 'craigslist.html' },
    { name: 'photo', url: 'craigslist.html' },
    { name: 'politics', url: 'craigslist.html' },
    { name: 'psych', url: 'craigslist.html' },
    { name: 'recover', url: 'craigslist.html' },
    { name: 'religion', url: 'craigslist.html' },
    { name: 'rofo', url: 'craigslist.html' },
    { name: 'science', url: 'craigslist.html' },
    { name: 'spirit', url: 'craigslist.html' },
    { name: 'sports', url: 'craigslist.html' },
    { name: 'super', url: 'craigslist.html' },
    { name: 'tax', url: 'craigslist.html' },
    { name: 'travel', url: 'craigslist.html' },
    { name: 'tv', url: 'craigslist.html' },
    { name: 'vegan', url: 'craigslist.html' },
    { name: 'words', url: 'craigslist.html' },
    { name: 'writing', url: 'craigslist.html' },

    // Add more nations as needed
  ];

  // Function to filter nations based on user input
  function filterNations(event) {
    const searchValue = event.target.value.toLowerCase();
    const dropdown = document.getElementById('nationDropdown');
    dropdown.innerHTML = '';

    const filteredNations = nations.filter(nation => nation.name.toLowerCase().startsWith(searchValue));
    filteredNations.forEach(nation => {
      const item = document.createElement('div');
      item.textContent = nation.name;
      item.classList.add('dropdown-menu-item');
      item.onclick = () => {
        window.location.href = nation.url;
      };
      dropdown.appendChild(item);
    });
  }
  // Event listener to close the dropdown menu when clicking outside
  document.addEventListener('click', function(event) {
    const dropdown = document.getElementById('nationDropdown');
    if (!dropdown.contains(event.target)) {
      dropdown.innerHTML = '';
    }
  });